### ISSUE TITLE
Suggestion: --> replaced with -> <-

### ISSUE THREAD

**Issue by ghost** [mark-hahn/csyn#1]
Hello,
I think csyn is a good idea. Let me make one suggestion:
I like return new syntax <- and I like -> too but I don't like them together. For example:

```
var square = (x) -> <- x * x
```

I think -> <- is quite noisy. So I suggest something like --> as replacemente:

```
var square = (x) --> x * x
```

Thank you for your attention.

**Comment by ghost** [comment]
I respond to myself.
Thin arrow (->) could work like ES6 fat arrow (=>) in the sense that it returns implicitely at one-line statement (not block statement). So instead: 

```
var square = (x) -> <- x * x
```

we'd have just

```
var square = (x) -> x * x
```

If you don't want return nothing:

```
var square = (x) ->
  console.log x * x
```

**Comment by mark-hahn** [comment]
Yeah, I noticed how ugly -> <- was.  The good thing is that it will be easy
to try different things.

BTW, I'm moving this project over to mark-hahn/anysyn.  Check it out.

**Comment by ampcpmgp** [comment]
にわたんやらな（お）？

**Comment by mark-hahn** [comment]
>   にわたんやらな（お）？

The google translation says "In such Yara Watan ( e)". Can someone give me
a better translation?

**Comment by ampcpmgp** [comment]
I'm sorry.. my mistake..
